import { jsPDF } from "jspdf";
import QRCode from "qrcode";
import { QrPayload, RetirementRecord, CarbonProject } from "../types";

// Helper to generate QR Base64
const generateQrCode = async (payload: QrPayload): Promise<string> => {
  try {
    const jsonStr = JSON.stringify(payload);
    return await QRCode.toDataURL(jsonStr, { errorCorrectionLevel: 'M', margin: 1 });
  } catch (err) {
    console.error("QR Generation Error", err);
    return "";
  }
};

// Store last generated QR for Demo Simulator
let lastGeneratedQrPayload: QrPayload | null = null;
export const getLastGeneratedQr = () => lastGeneratedQrPayload;

// --- LAYOUT CONFIG ---
const CONFIG = {
  margin: 15,
  colLabelX: 55,
  colValueX: 95,
  qrX: 215,
  qrY: 75,
  qrSize: 40,
  separatorY: 135
};

export const pdfService = {
  
  generateMintCertificate: async (
    project: CarbonProject, 
    batchId: string, 
    txHash: string
  ) => {
    // 1. Setup Landscape A4
    const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth(); // 297mm
    const pageHeight = doc.internal.pageSize.getHeight(); // 210mm
    const centerX = pageWidth / 2;
    
    // 2. Prepare QR Payload
    const payload: QrPayload = {
      type: 'MINT_CERT',
      version: '1.0',
      contract: 'XRPL',
      network: 'TESTNET',
      data: {
        tokenId: project.tokenTicker,
        batchId: batchId,
        amount: project.availableSupply,
        txHash: txHash,
        timestamp: new Date().toISOString(),
        status: 'ISSUED'
      }
    };
    lastGeneratedQrPayload = payload;
    const qrDataUrl = await generateQrCode(payload);

    // --- VISUAL DESIGN ---

    // Border (Green)
    doc.setDrawColor(16, 185, 129); // Emerald 500
    doc.setLineWidth(3);
    doc.rect(CONFIG.margin, CONFIG.margin, pageWidth - (CONFIG.margin * 2), pageHeight - (CONFIG.margin * 2));

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(32);
    doc.setTextColor(16, 185, 129); // Green text
    doc.text("CARBON CREDIT CERTIFICATE", centerX, 50, { align: "center" });

    // Subtitle
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold"); // Semi-bold look
    doc.setTextColor(60, 60, 60);
    doc.text("This certifies the issuance of verified carbon credits.", centerX, 65, { align: "center" });

    // --- DATA SECTION TOP (Asset Details) ---
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);

    let y = 85;
    const gap = 12;

    // Row 1
    doc.setFont("helvetica", "bold"); doc.text("Project ID:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(`VCS-${project.id} (Verified)`, CONFIG.colValueX, y);
    y += gap;

    // Row 2
    doc.setFont("helvetica", "bold"); doc.text("Methodology:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(`${project.standard} (VM0007)`, CONFIG.colValueX, y);
    y += gap;

    // Row 3
    doc.setFont("helvetica", "bold"); doc.text("Amount:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(`${project.availableSupply.toLocaleString()} tCO2e`, CONFIG.colValueX, y);
    y += gap;

    // Row 4
    doc.setFont("helvetica", "bold"); doc.text("Location:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(project.location, CONFIG.colValueX, y);
    y += gap;

    // Row 5
    doc.setFont("helvetica", "bold"); doc.text("Token ID:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(project.tokenTicker, CONFIG.colValueX, y);

    // --- QR CODE SECTION ---
    doc.addImage(qrDataUrl, "PNG", CONFIG.qrX, CONFIG.qrY, CONFIG.qrSize, CONFIG.qrSize);
    
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    doc.text("Scan to Verify", CONFIG.qrX + (CONFIG.qrSize / 2), CONFIG.qrY + CONFIG.qrSize + 6, { align: "center" });

    // --- SEPARATOR ---
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(2);
    doc.line(CONFIG.colLabelX, CONFIG.separatorY, pageWidth - CONFIG.colLabelX, CONFIG.separatorY);

    // --- DATA SECTION BOTTOM (Transaction Details) ---
    y = 155;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);

    // Row 1
    doc.setFont("helvetica", "bold"); doc.text("Mint Tx Hash:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(txHash, CONFIG.colValueX, y);
    y += gap;

    // Row 2
    doc.setFont("helvetica", "bold"); doc.text("Date:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(new Date().toISOString().replace('T', ' ').substring(0, 19) + ' UTC', CONFIG.colValueX, y);

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by EcoLedger XRPL • ${new Date().toLocaleDateString()}`, centerX, pageHeight - 20, { align: "center" });

    doc.save(`${project.tokenTicker}_MINT_CERT.pdf`);
  },

  generateRetirementCertificate: async (
    record: RetirementRecord, 
    ticker: string
  ) => {
    // 1. Setup Landscape A4
    const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth(); 
    const pageHeight = doc.internal.pageSize.getHeight();
    const centerX = pageWidth / 2;

    // 2. Prepare QR Payload
    const payload: QrPayload = {
      type: 'RETIREMENT_CERT',
      version: '1.0',
      contract: 'XRPL',
      network: 'TESTNET',
      data: {
        tokenId: ticker,
        amount: record.amount,
        txHash: record.txHash,
        timestamp: record.timestamp.toISOString(),
        status: 'RETIRED'
      }
    };
    lastGeneratedQrPayload = payload;
    const qrDataUrl = await generateQrCode(payload);

    // --- VISUAL DESIGN ---

    // Border (Orange)
    doc.setDrawColor(234, 88, 12); // Orange 600
    doc.setLineWidth(3);
    doc.rect(CONFIG.margin, CONFIG.margin, pageWidth - (CONFIG.margin * 2), pageHeight - (CONFIG.margin * 2));

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(32);
    doc.setTextColor(234, 88, 12); // Orange text
    doc.text("CERTIFICATE OF RETIREMENT", centerX, 50, { align: "center" });

    // Subtitle
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text("This certifies that carbon credits have been permanently retired.", centerX, 65, { align: "center" });

    // --- DATA SECTION TOP ---
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);

    let y = 85;
    const gap = 12;

    // Row 1
    doc.setFont("helvetica", "bold"); doc.text("Project ID:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text("VCS-1845", CONFIG.colValueX, y); // Using static demo ID for consistent look
    y += gap;

    // Row 2
    doc.setFont("helvetica", "bold"); doc.text("Methodology:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text("VM0007 (REDD+)", CONFIG.colValueX, y);
    y += gap;

    // Row 3
    doc.setFont("helvetica", "bold"); doc.text("Amount:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(`${record.amount.toLocaleString()} tCO2e`, CONFIG.colValueX, y);
    y += gap;

    // Row 4
    doc.setFont("helvetica", "bold"); doc.text("Location:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text("Amazonas, Brazil", CONFIG.colValueX, y); // Demo data match
    y += gap;

    // Row 5
    doc.setFont("helvetica", "bold"); doc.text("Token ID:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(ticker, CONFIG.colValueX, y);

    // --- QR CODE ---
    doc.addImage(qrDataUrl, "PNG", CONFIG.qrX, CONFIG.qrY, CONFIG.qrSize, CONFIG.qrSize);
    
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    doc.text("Scan to Verify", CONFIG.qrX + (CONFIG.qrSize / 2), CONFIG.qrY + CONFIG.qrSize + 6, { align: "center" });

    // --- SEPARATOR ---
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(2);
    doc.line(CONFIG.colLabelX, CONFIG.separatorY, pageWidth - CONFIG.colLabelX, CONFIG.separatorY);

    // --- DATA SECTION BOTTOM ---
    y = 155;
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);

    // Row 1
    doc.setFont("helvetica", "bold"); doc.text("Retired For:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(record.purpose, CONFIG.colValueX, y);
    y += gap;

    // Row 2
    doc.setFont("helvetica", "bold"); doc.text("Burn Tx Hash:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(record.txHash, CONFIG.colValueX, y);
    y += gap;

    // Row 3
    doc.setFont("helvetica", "bold"); doc.text("Date:", CONFIG.colLabelX, y);
    doc.setFont("helvetica", "normal"); doc.text(new Date(record.timestamp).toISOString().replace('T', ' ').substring(0, 19) + ' UTC', CONFIG.colValueX, y);

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by EcoLedger XRPL • ${new Date().toLocaleDateString()}`, centerX, pageHeight - 20, { align: "center" });

    doc.save(`${ticker}_OFFSET_PROOF.pdf`);
  }
};
